{
  "name": "telegram-wallet-connect",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@web3modal/wagmi": "^3.5.0",
    "viem": "^2.7.12", 
    "wagmi": "^2.5.7"
  },
  "devDependencies": {
    "vite": "^5.0.10"
  },
  "overrides": {
    "viem": "^2.7.12",
    "wagmi": "^2.5.7"
  },
  "engines": {
    "node": ">=18.0.0"
  }
}
